[pytest]
DJANGO_SETTINGS_MODULE = ojt_backend.settings
pythonpath = backend
testpaths = backend/security/tests
python_files = tests.py test_*.py *_tests.py *_whitebox.py
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
addopts = -v
