services:
  - type: web
    name: web
    env: static
    buildCommand: "npm run build"
    startCommand: "serve -s dist"
    publishPath: "dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"