import json
from django.conf import settings
from django.core.mail import send_mail
from django.http import JsonResponse, HttpRequest
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods

from .api_auth import require_jwt
from .models import (
    Student, OJTInstructor, HTE, StudentOJTApplication, TimeRecord, HTEAccessRequest, RegistrationOTPRequest
)
from .models import OTPVerification, OTPAuditLog
from django.db import models
from .api_auth import require_jwt

def send_application_status_email(email: str, student_name: str, status: str, company_name: str = "") -> bool:
    """Send application status update email."""
    try:
        subject = f"OJT Application {status.capitalize()}"
        message = f"""
Hello {student_name},

Your OJT application has been {status}.

{"Company: " + company_name if company_name else ""}

For more details, please log in to your dashboard.

Best regards,
OJT Management System
        """
        send_mail(
            subject,
            message,
            settings.DEFAULT_FROM_EMAIL,
            [email],
            fail_silently=False,
        )
        return True
    except Exception as e:
        print(f"Error sending email: {e}")
        return False

@csrf_exempt
@require_http_methods(["POST"])
def submit_ojt_application(request: HttpRequest) -> JsonResponse:
    """Submit OJT application from student."""
    try:
        data = json.loads(request.body)
        user_id = data.get('user_id')
        instructor_id = data.get('instructor_id')
        company_name = data.get('company_name', '').strip()
        company_address = data.get('company_address', '').strip()
        gps_lat = data.get('gps_latitude')
        gps_lng = data.get('gps_longitude')
        geofence_radius = data.get('geofence_radius', 100)
        start_date = data.get('start_date')
        end_date = data.get('end_date')
        required_hours = data.get('required_hours')
        
        if not all([user_id, instructor_id, company_name, company_address, gps_lat, gps_lng, start_date, end_date, required_hours]):
            return JsonResponse({'error': 'Missing required fields'}, status=400)
        
        try:
            student = Student.objects.get(user_id=user_id)
            instructor = OJTInstructor.objects.get(id=instructor_id)
        except (Student.DoesNotExist, OJTInstructor.DoesNotExist):
            return JsonResponse({'error': 'Student or instructor not found'}, status=404)

        # Enforce instructor OTP validation: trainee must provide otp_code generated by instructor
        otp_code = data.get('otp_code')
        if not otp_code:
            return JsonResponse({'error': 'otp_code is required to submit application'}, status=403)

        try:
            otp_obj = OTPVerification.objects.filter(email__iexact=instructor.user.email, otp_code=otp_code).order_by('-created_at').first()
            if not otp_obj or not otp_obj.is_valid():
                return JsonResponse({'error': 'Invalid or expired OTP code'}, status=403)
            # mark as used
            otp_obj.is_verified = True
            otp_obj.save()
            # audit
            try:
                ip = request.META.get('REMOTE_ADDR') or request.META.get('HTTP_X_FORWARDED_FOR', '')
                OTPAuditLog.objects.create(action='validate', email=instructor.user.email, otp_code=otp_code, actor=None, ip_address=str(ip))
            except Exception:
                pass
        except Exception:
            return JsonResponse({'error': 'OTP validation failed'}, status=500)
        
        application = StudentOJTApplication.objects.create(
            student=student,
            instructor=instructor,
            company_name=company_name,
            company_address=company_address,
            gps_latitude=float(gps_lat),
            gps_longitude=float(gps_lng),
            geofence_radius=float(geofence_radius),
            start_date=start_date,
            end_date=end_date,
            required_hours=int(required_hours),
            status='pending'
        )
        
        send_mail(
            'New OJT Application Submitted',
            f"New OJT application from {student.user.get_full_name()} for {company_name}",
            settings.DEFAULT_FROM_EMAIL,
            [instructor.user.email],
            fail_silently=True
        )
        
        return JsonResponse({
            'success': True,
            'message': 'OJT application submitted successfully',
            'application_id': application.id
        }, status=201)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

@csrf_exempt
@require_http_methods(["POST"])
@require_jwt(required_role='instructor')
def approve_ojt_application(request: HttpRequest) -> JsonResponse:
    """Approve OJT application (instructor only)."""
    try:
        data = json.loads(request.body)
        application_id = data.get('application_id')

        if not application_id:
            return JsonResponse({'error': 'Application ID required'}, status=400)

        try:
            application = StudentOJTApplication.objects.get(id=application_id)
        except StudentOJTApplication.DoesNotExist:
            return JsonResponse({'error': 'Application not found'}, status=404)

        # Only the assigned instructor may approve
        user = getattr(request, 'user', None)
        instructor = OJTInstructor.objects.filter(user=user).first()
        if not instructor or application.instructor_id != instructor.id:
            return JsonResponse({'error': 'Not authorized to approve this application'}, status=403)

        application.status = 'approved'
        application.approved_at = timezone.now()
        application.save()

        send_application_status_email(
            application.student.user.email,
            application.student.user.get_full_name(),
            'approved',
            application.company_name
        )

        # Optional: sync status to Supabase employees table if configured
        try:
            supabase_url = getattr(settings, 'SUPABASE_URL', None) or getattr(settings, 'VITE_SUPABASE_URL', None)
            supabase_key = getattr(settings, 'SUPABASE_SERVICE_KEY', None) or getattr(settings, 'VITE_SUPABASE_SERVICE_KEY', None)
            if supabase_url and supabase_key:
                import urllib.request
                import urllib.parse
                sup_rest = supabase_url.rstrip('/') + '/rest/v1/employees'
                # Patch by email
                email_q = urllib.parse.quote_plus(f"email=eq.{application.student.user.email}")
                url = f"{sup_rest}?{email_q}"
                payload = json.dumps({"application_status": "approved"}).encode('utf-8')
                req = urllib.request.Request(url, data=payload, method='PATCH')
                req.add_header('Content-Type', 'application/json')
                req.add_header('Prefer', 'return=representation')
                req.add_header('apikey', supabase_key)
                req.add_header('Authorization', f'Bearer {supabase_key}')
                try:
                    with urllib.request.urlopen(req, timeout=6) as resp:
                        _ = resp.read()
                except Exception as exc:
                    # log and continue
                    print('Supabase sync failed:', exc)
        except Exception:
            pass

        return JsonResponse({'success': True, 'message': 'Application approved successfully'})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

@csrf_exempt
@require_http_methods(["POST"])
@require_jwt(required_role='instructor')
def reject_ojt_application(request: HttpRequest) -> JsonResponse:
    """Reject OJT application (instructor only)."""
    try:
        data = json.loads(request.body)
        application_id = data.get('application_id')
        rejection_reason = data.get('rejection_reason', '')

        if not application_id:
            return JsonResponse({'error': 'Application ID required'}, status=400)

        try:
            application = StudentOJTApplication.objects.get(id=application_id)
        except StudentOJTApplication.DoesNotExist:
            return JsonResponse({'error': 'Application not found'}, status=404)

        # Only the assigned instructor may reject
        user = getattr(request, 'user', None)
        instructor = OJTInstructor.objects.filter(user=user).first()
        if not instructor or application.instructor_id != instructor.id:
            return JsonResponse({'error': 'Not authorized to reject this application'}, status=403)

        application.status = 'rejected'
        application.rejection_reason = rejection_reason
        application.save()

        send_application_status_email(
            application.student.user.email,
            application.student.user.get_full_name(),
            'rejected',
            application.company_name
        )

        return JsonResponse({'success': True, 'message': 'Application rejected successfully'})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

@csrf_exempt
@require_http_methods(["GET"])
@require_jwt(required_role='hte')
def get_hte_applications(request: HttpRequest) -> JsonResponse:
    """Return OJT applications associated with an HTE user."""
    try:
        user = getattr(request, 'user', None)
        hte = HTE.objects.filter(user=user).first()
        if not hte:
            return JsonResponse({'error': 'HTE profile not found'}, status=404)

        applications = StudentOJTApplication.objects.filter(hte=hte).order_by('-created_at')
        data = [
            {
                'id': a.id,
                'student_name': a.student.user.get_full_name(),
                'student_email': a.student.user.email,
                'status': a.status,
                'required_hours': a.required_hours,
                'rendered_hours': a.rendered_hours,
                'remaining_hours': a.remaining_hours, # Accessing as property now
                'start_date': a.start_date.isoformat(),
                'end_date': a.end_date.isoformat(),
                'company_name': a.company_name,
            }
            for a in applications
        ]

        return JsonResponse({'success': True, 'applications': data})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["GET"])
@require_jwt(required_role='instructor')
def get_instructor_applications(request: HttpRequest) -> JsonResponse:
    """Return OJT applications associated with the authenticated instructor."""
    try:
        user = getattr(request, 'user', None)
        instructor = OJTInstructor.objects.filter(user=user).first()
        if not instructor:
            return JsonResponse({'error': 'Instructor profile not found'}, status=404)
        # Support pagination and simple search
        q = request.GET.get('q', '').strip()
        try:
            page = int(request.GET.get('page', '1'))
        except Exception:
            page = 1
        try:
            page_size = int(request.GET.get('page_size', '20'))
        except Exception:
            page_size = 20

        qs = StudentOJTApplication.objects.filter(instructor=instructor)
        if q:
            qs = qs.filter(
                models.Q(student__user__first_name__icontains=q) |
                models.Q(student__user__last_name__icontains=q) |
                models.Q(student__user__email__icontains=q) |
                models.Q(company_name__icontains=q)
            )

        total = qs.count()
        start = (page - 1) * page_size
        end = start + page_size
        applications = qs.order_by('-created_at')[start:end]

        data = [
            {
                'id': a.id,
                'student_id': a.student.user.id,
                'student_name': a.student.user.get_full_name(),
                'student_email': a.student.user.email,
                'status': a.status,
                'required_hours': a.required_hours,
                'rendered_hours': a.rendered_hours,
                'remaining_hours': a.remaining_hours,
                'start_date': a.start_date.isoformat(),
                'end_date': a.end_date.isoformat(),
                'company_name': a.company_name,
                'company_address': a.company_address,
            }
            for a in applications
        ]

        return JsonResponse({'success': True, 'applications': data, 'total': total, 'page': page, 'page_size': page_size})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["GET"])
@require_jwt(required_role='instructor')
def get_application_time_records(request: HttpRequest) -> JsonResponse:
    """Return time records for a specific application (instructor access only)."""
    try:
        application_id = request.GET.get('application_id')
        if not application_id:
            return JsonResponse({'error': 'application_id is required'}, status=400)

        try:
            application = StudentOJTApplication.objects.get(id=application_id)
        except StudentOJTApplication.DoesNotExist:
            return JsonResponse({'error': 'Application not found'}, status=404)

        # Ensure the requesting instructor owns this application
        user = getattr(request, 'user', None)
        instructor = OJTInstructor.objects.filter(user=user).first()
        if not instructor or application.instructor.id != instructor.id:
            return JsonResponse({'error': 'Not authorized to view this application'}, status=403)

        records = TimeRecord.objects.filter(application=application).order_by('-date')
        data = [
            {
                'id': r.id,
                'date': r.date.isoformat(),
                'time_in': r.time_in.isoformat() if r.time_in else None,
                'time_out': r.time_out.isoformat() if r.time_out else None,
                'hours_rendered': r.hours_rendered,
                'session': r.session,
                'is_approved': r.is_approved,
                'notes': r.notes,
            }
            for r in records
        ]

        return JsonResponse({'success': True, 'time_records': data})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

@csrf_exempt
@require_http_methods(["GET"])
@require_jwt(required_role='hte')
def get_hte_access_requests(request: HttpRequest) -> JsonResponse:
    """Return HTE access requests for the HTE user."""
    try:
        user = getattr(request, 'user', None)
        hte = HTE.objects.filter(user=user).first()
        if not hte:
            return JsonResponse({'error': 'HTE profile not found'}, status=404)

        requests = HTEAccessRequest.objects.filter(hte=hte).order_by('-requested_at')
        data = [
            {
                'id': r.id,
                'application_id': r.application.id,
                'student_name': r.application.student.user.get_full_name(),
                'status': r.status,
                'requested_at': r.requested_at.isoformat(),
                'approved_at': r.approved_at.isoformat() if r.approved_at else None,
                'rejection_reason': r.rejection_reason,
            }
            for r in requests
        ]

        return JsonResponse({'success': True, 'access_requests': data})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

@csrf_exempt
@require_http_methods(["GET"])
@require_jwt(required_role='hte')
def get_hte_dashboard(request: HttpRequest) -> JsonResponse:
    """Return aggregate dashboard metrics for the authenticated HTE."""
    try:
        user = getattr(request, 'user', None)
        hte = HTE.objects.filter(user=user).first()
        if not hte:
            return JsonResponse({'error': 'HTE profile not found'}, status=404)

        applications = StudentOJTApplication.objects.filter(hte=hte)
        total_applications = applications.count()
        status_counts = {
            'pending': applications.filter(status='pending').count(),
            'approved': applications.filter(status='approved').count(),
            'rejected': applications.filter(status='rejected').count(),
            'completed': applications.filter(status='completed').count(),
            'cancelled': applications.filter(status='cancelled').count(),
        }

        total_required_hours = sum(a.required_hours for a in applications)
        total_rendered_hours = sum(a.rendered_hours for a in applications)
        total_remaining_hours = sum(a.remaining_hours for a in applications) # Accessing as property now

        unique_students = applications.values_list('student__user__id', flat=True).distinct().count()

        recent_time_records = TimeRecord.objects.filter(application__in=applications).order_by('-date')[:20]
        recent = [
            {
                'id': t.id,
                'student_name': t.student.user.get_full_name(),
                'date': t.date.isoformat(),
                'hours_rendered': t.hours_rendered,
                'is_approved': t.is_approved,
            }
            for t in recent_time_records
        ]

        return JsonResponse({
            'success': True,
            'metrics': {
                'total_applications': total_applications,
                'status_counts': status_counts,
                'total_required_hours': total_required_hours,
                'total_rendered_hours': total_rendered_hours,
                'total_remaining_hours': total_remaining_hours,
                'unique_students': unique_students,
            },
            'recent_time_records': recent,
        })
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["GET"])
@require_jwt()
def get_my_application_status(request: HttpRequest) -> JsonResponse:
    """Return the authenticated student's latest application status."""
    try:
        user = getattr(request, 'user', None)
        if not user:
            return JsonResponse({'error': 'authorization_required'}, status=401)

        student = Student.objects.filter(user=user).first()
        if not student:
            return JsonResponse({'error': 'Student profile not found'}, status=404)

        app = StudentOJTApplication.objects.filter(student=student).order_by('-created_at').first()
        if not app:
            return JsonResponse({'success': True, 'application': None})

        data = {
            'id': app.id,
            'status': app.status,
            'company_name': app.company_name,
            'start_date': app.start_date.isoformat(),
            'end_date': app.end_date.isoformat(),
            'required_hours': app.required_hours,
            'rendered_hours': app.rendered_hours,
        }
        return JsonResponse({'success': True, 'application': data})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

@csrf_exempt
@require_http_methods(["POST"])
def request_hte_access(request: HttpRequest) -> JsonResponse:
    """Request HTE access for student application."""
    try:
        data = json.loads(request.body)
        application_id = data.get('application_id')
        hte_id = data.get('hte_id')
        
        if not all([application_id, hte_id]):
            return JsonResponse({'error': 'Application ID and HTE ID required'}, status=400)
        
        try:
            application = StudentOJTApplication.objects.get(id=application_id)
            hte = HTE.objects.get(id=hte_id)
        except (StudentOJTApplication.DoesNotExist, HTE.DoesNotExist):
            return JsonResponse({'error': 'Application or HTE not found'}, status=404)
        
        application.hte = hte
        application.save()
        
        access_request = HTEAccessRequest.objects.create(
            hte=hte,
            application=application,
            status='pending'
        )
        
        send_mail(
            'New HTE Access Request',
            f"New access request from {application.student.user.get_full_name()} for {application.company_name}",
            settings.DEFAULT_FROM_EMAIL,
            [hte.user.email],
            fail_silently=True
        )
        
        return JsonResponse({
            'success': True,
            'message': 'HTE access request submitted successfully',
            'request_id': access_request.id
        }, status=201)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

@csrf_exempt
@require_http_methods(["POST"])
def approve_hte_access(request: HttpRequest) -> JsonResponse:
    """Approve HTE access request."""
    try:
        data = json.loads(request.body)
        request_id = data.get('request_id')
        
        if not request_id:
            return JsonResponse({'error': 'Request ID required'}, status=400)
        
        try:
            access_request = HTEAccessRequest.objects.get(id=request_id)
        except HTEAccessRequest.DoesNotExist:
            return JsonResponse({'error': 'Access request not found'}, status=404)
        
        access_request.status = 'approved'
        access_request.approved_at = timezone.now()
        access_request.save()
        
        return JsonResponse({'success': True, 'message': 'HTE access approved successfully'})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

@csrf_exempt
@require_http_methods(["POST"])
def reject_hte_access(request: HttpRequest) -> JsonResponse:
    """Reject HTE access request."""
    try:
        data = json.loads(request.body)
        request_id = data.get('request_id')
        rejection_reason = data.get('rejection_reason', '')
        
        if not request_id:
            return JsonResponse({'error': 'Request ID required'}, status=400)
        
        try:
            access_request = HTEAccessRequest.objects.get(id=request_id)
        except HTEAccessRequest.DoesNotExist:
            return JsonResponse({'error': 'Access request not found'}, status=404)
        
        access_request.status = 'rejected'
        access_request.rejection_reason = rejection_reason
        access_request.save()
        
        return JsonResponse({'success': True, 'message': 'HTE access rejected successfully'})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


# ========== REGISTRATION OTP REQUEST FLOW ==========

@csrf_exempt
@require_http_methods(["POST"])
def request_registration_otp(request: HttpRequest) -> JsonResponse:
    """
    Trainee or HTE requests OTP before completing registration.
    Generates OTP and sends it to the instructor's email.
    """
    from .models import RegistrationOTPRequest
    import random
    import string
    
    try:
        data = json.loads(request.body)
        
        role = data.get('role', '').strip()  # 'trainee' or 'hte'
        email = data.get('email', '').strip()
        phone = data.get('phone', '').strip()
        first_name = data.get('first_name', '').strip()
        last_name = data.get('last_name', '').strip()
        instructor_id = data.get('instructor_id')
        
        # Validation
        if not all([role, email, first_name, last_name, instructor_id]):
            return JsonResponse({'error': 'Missing required fields'}, status=400)
        
        if role not in ['trainee', 'hte']:
            return JsonResponse({'error': 'Invalid role'}, status=400)
        
        # Check email not already registered
        if models.User.objects.filter(email=email).exists():
            return JsonResponse({'error': 'Email already registered'}, status=400)
        
        # Check instructor exists
        try:
            instructor = OJTInstructor.objects.get(id=instructor_id)
        except OJTInstructor.DoesNotExist:
            return JsonResponse({'error': 'Instructor not found'}, status=404)
        
        # Generate OTP
        otp_code = ''.join(random.choices(string.digits, k=6))
        
        # Create RegistrationOTPRequest
        reg_request = RegistrationOTPRequest.objects.create(
            role=role,
            email=email,
            phone=phone,
            first_name=first_name,
            last_name=last_name,
            instructor=instructor,
            otp_code=otp_code,
            status='pending'
        )
        
        # If HTE, capture company info
        if role == 'hte':
            reg_request.company_name = data.get('company_name', '').strip()
            reg_request.company_address = data.get('company_address', '').strip()
            reg_request.contact_person = data.get('contact_person', '').strip()
            reg_request.barangay = data.get('barangay', '').strip()
            reg_request.save()
        
        # If trainee, capture student info
        if role == 'trainee':
            reg_request.student_id = data.get('student_id', '').strip()
            reg_request.school_name = data.get('school_name', '').strip()
            reg_request.course = data.get('course', '').strip()
            reg_request.year_level = data.get('year_level', '').strip()
            reg_request.save()
        
        # Send OTP to instructor email
        subject = f"New Registration Request - {first_name} {last_name} ({role.upper()})"
        message = f"""
Hello {instructor.user.get_full_name()},

A new {role} has requested to register with the OJT system.

Name: {first_name} {last_name}
Email: {email}
Role: {role.upper()}

OTP Code: {otp_code}

Please review and approve/reject this registration request in your dashboard.

Best regards,
OJT Management System
        """
        try:
            send_mail(
                subject,
                message,
                settings.DEFAULT_FROM_EMAIL,
                [instructor.user.email],
                fail_silently=False
            )
        except Exception as e:
            print(f"Error sending OTP email: {e}")
        
        return JsonResponse({
            'success': True,
            'message': 'OTP request submitted. Instructor will receive OTP code for verification.',
            'request_id': reg_request.id,
            'otp_code': otp_code  # For development/testing; remove in production
        }, status=201)
    
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["GET"])
@require_jwt(required_role='instructor')
def get_pending_registration_requests(request: HttpRequest) -> JsonResponse:
    """
    Get pending registration OTP requests for the authenticated instructor.
    """
    from .models import RegistrationOTPRequest
    
    try:
        user = getattr(request, 'user', None)
        instructor = OJTInstructor.objects.filter(user=user).first()
        
        if not instructor:
            return JsonResponse({'error': 'Instructor profile not found'}, status=404)
        
        # Get pending requests
        pending_requests = RegistrationOTPRequest.objects.filter(
            instructor=instructor,
            status='pending'
        ).order_by('-requested_at')
        
        data = [
            {
                'id': req.id,
                'role': req.role,
                'first_name': req.first_name,
                'last_name': req.last_name,
                'email': req.email,
                'phone': req.phone,
                'otp_code': req.otp_code,
                # HTE fields
                'company_name': req.company_name,
                'company_address': req.company_address,
                'contact_person': req.contact_person,
                'barangay': req.barangay,
                # Trainee fields
                'student_id': req.student_id,
                'school_name': req.school_name,
                'course': req.course,
                'year_level': req.year_level,
                # Status
                'requested_at': req.requested_at.isoformat(),
                'status': req.status,
            }
            for req in pending_requests
        ]
        
        return JsonResponse({
            'success': True,
            'pending_requests': data,
            'count': len(data)
        })
    
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["POST"])
@require_jwt(required_role='instructor')
def approve_registration_request(request: HttpRequest) -> JsonResponse:
    """
    Instructor approves a pending registration OTP request.
    """
    from .models import RegistrationOTPRequest, UserRole
    
    try:
        user = getattr(request, 'user', None)
        instructor = OJTInstructor.objects.filter(user=user).first()
        
        if not instructor:
            return JsonResponse({'error': 'Instructor profile not found'}, status=404)
        
        data = json.loads(request.body)
        request_id = data.get('request_id')
        
        if not request_id:
            return JsonResponse({'error': 'request_id is required'}, status=400)
        
        try:
            reg_request = RegistrationOTPRequest.objects.get(id=request_id)
        except RegistrationOTPRequest.DoesNotExist:
            return JsonResponse({'error': 'Request not found'}, status=404)
        
        # Check instructor is the one this request is for
        if reg_request.instructor_id != instructor.id:
            return JsonResponse({'error': 'Not authorized'}, status=403)
        
        if reg_request.status != 'pending':
            return JsonResponse({'error': f'Request status is {reg_request.status}, cannot approve'}, status=400)
        
        # Mark as approved
        reg_request.status = 'approved'
        reg_request.approved_at = timezone.now()
        reg_request.approved_by = user
        reg_request.save()
        
        # Send approval email to trainee/HTE
        subject = "Registration Approved - OJT System"
        message = f"""
Hello {reg_request.first_name} {reg_request.last_name},

Your registration request has been approved!

You can now proceed with the following steps:
1. Complete facial recognition
2. Set up your company/workplace information
3. Configure geofencing details

Your approval code: {reg_request.otp_code}

Please log in to your dashboard and complete the remaining steps.

Best regards,
OJT Management System
        """
        try:
            send_mail(
                subject,
                message,
                settings.DEFAULT_FROM_EMAIL,
                [reg_request.email],
                fail_silently=False
            )
        except Exception as e:
            print(f"Error sending approval email: {e}")
        
        return JsonResponse({
            'success': True,
            'message': 'Registration request approved. Trainee/HTE will receive approval email.',
            'request_id': reg_request.id
        })
    
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)


@csrf_exempt
@require_http_methods(["POST"])
@require_jwt(required_role='instructor')
def reject_registration_request(request: HttpRequest) -> JsonResponse:
    """
    Instructor rejects a pending registration OTP request.
    """
    from .models import RegistrationOTPRequest
    
    try:
        user = getattr(request, 'user', None)
        instructor = OJTInstructor.objects.filter(user=user).first()
        
        if not instructor:
            return JsonResponse({'error': 'Instructor profile not found'}, status=404)
        
        data = json.loads(request.body)
        request_id = data.get('request_id')
        rejection_reason = data.get('rejection_reason', '')
        
        if not request_id:
            return JsonResponse({'error': 'request_id is required'}, status=400)
        
        try:
            reg_request = RegistrationOTPRequest.objects.get(id=request_id)
        except RegistrationOTPRequest.DoesNotExist:
            return JsonResponse({'error': 'Request not found'}, status=404)
        
        # Check instructor is the one this request is for
        if reg_request.instructor_id != instructor.id:
            return JsonResponse({'error': 'Not authorized'}, status=403)
        
        if reg_request.status != 'pending':
            return JsonResponse({'error': f'Request status is {reg_request.status}, cannot reject'}, status=400)
        
        # Mark as rejected
        reg_request.status = 'rejected'
        reg_request.rejection_reason = rejection_reason
        reg_request.save()
        
        # Send rejection email
        subject = "Registration Request Rejected - OJT System"
        message = f"""
Hello {reg_request.first_name} {reg_request.last_name},

Unfortunately, your registration request has been rejected.

Reason: {rejection_reason or 'No reason provided'}

Please contact the OJT Instructor for more information.

Best regards,
OJT Management System
        """
        try:
            send_mail(
                subject,
                message,
                settings.DEFAULT_FROM_EMAIL,
                [reg_request.email],
                fail_silently=False
            )
        except Exception as e:
            print(f"Error sending rejection email: {e}")
        
        return JsonResponse({
            'success': True,
            'message': 'Registration request rejected.',
            'request_id': reg_request.id
        })
    
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)
