/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wooighmdckuoebsuegzz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indvb2lnaG1kY2t1b2Vic3VlZ3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2OTE4MDcsImV4cCI6MjA4ODI2NzgwN30.ETVnzajdLNdezhh-lraSrubf1MC--VSyKKV3KUh9vWk"