# Generated by Django 4.2.30 on 2026-04-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('in', 'Time In'), ('out', 'Time Out')], max_length=8)),
                ('image', models.ImageField(upload_to='attendance_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=64, unique=True)),
                ('image', models.ImageField(upload_to='face_registrations/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
