# Generated by Django 4.2.30 on 2026-04-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_otpverification_attendancephoto_face_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20),
        ),
        migrations.CreateModel(
            name='AnnouncementSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcement_submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='security.announcement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_submissions', to='security.student')),
            ],
        ),
    ]
