# Generated by Django 4.2.30 on 2026-05-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_store_images_in_database'),
        ('security', '0003_timerecord_session_announcementsubmission'),
    ]

    operations = [
    ]
