# Generated by Django 4.2.30 on 2026-06-02 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0005_add_face_encoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('validate', 'Validated')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(blank=True, max_length=6)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
