# Generated by Django 4.2.30 on 2026-06-03 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0007_add_hte_barangay'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('trainee', 'Trainee'), ('hte', 'Host Training Establishment')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('barangay', models.CharField(blank=True, max_length=255)),
                ('student_id', models.CharField(blank=True, max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('course', models.CharField(blank=True, max_length=255)),
                ('year_level', models.CharField(blank=True, max_length=50)),
                ('otp_code', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending OTP Approval'), ('approved', 'Approved - Proceed to Registration'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('face_photo', models.ImageField(blank=True, null=True, upload_to='registration_face_photos/')),
                ('face_photo_url', models.URLField(blank=True, help_text='Supabase URL or other cloud storage URL')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_registrations', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='security.ojtinstructor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['instructor', 'status'], name='security_re_instruc_382e63_idx'), models.Index(fields=['email'], name='security_re_email_2d39b9_idx'), models.Index(fields=['otp_code'], name='security_re_otp_cod_ae08c4_idx')],
            },
        ),
    ]
