# Generated by Django 4.2.30 on 2026-06-03 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_registrationotprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeOTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('trainee', 'Trainee'), ('hte', 'HTE')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('barangay', models.CharField(blank=True, max_length=255)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('geofence_radius', models.FloatField(default=100.0)),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('course', models.CharField(blank=True, max_length=255)),
                ('year_level', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('face_photo', models.ImageField(blank=True, null=True, upload_to='face_registrations/')),
                ('face_data', models.TextField(blank=True, help_text='Facial recognition data/embedding')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('face_registered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_requests', to='security.ojtinstructor')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['email'], name='security_tr_email_6f047f_idx'), models.Index(fields=['status'], name='security_tr_status_42d2a5_idx'), models.Index(fields=['instructor', 'status'], name='security_tr_instruc_4ffaf2_idx')],
            },
        ),
    ]
