# Generated by Django 6.0.6 on 2026-06-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_traineeotprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeotprequest',
            name='avatar_key',
            field=models.CharField(blank=True, help_text='Object storage key for avatar', max_length=512),
        ),
        migrations.AddField(
            model_name='traineeotprequest',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='Direct URL to avatar in object storage'),
        ),
        migrations.AddField(
            model_name='traineeotprequest',
            name='face_registered',
            field=models.BooleanField(default=False, help_text='True when face is registered/enrolled'),
        ),
        migrations.AddField(
            model_name='traineeotprequest',
            name='gps_accuracy',
            field=models.FloatField(blank=True, help_text='Estimated accuracy in meters from device GPS', null=True),
        ),
        migrations.AddField(
            model_name='traineeotprequest',
            name='thumbnail_key',
            field=models.CharField(blank=True, help_text='Object storage key for avatar thumbnail', max_length=512),
        ),
    ]
