# Generated by Django 4.2.30 on 2026-09-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_traineeotprequest_avatar_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='time_in_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='time_in_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='time_out_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='time_out_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
